# Practical : 12
## Aim :  Case study/Project: Implementation of any real time application using suitable machine learning technique.

In [1]:
import pandas as pd
import numpy as np

In [2]:
from sklearn import preprocessing
from sklearn.feature_selection import SelectKBest, f_regression
from sklearn.model_selection import train_test_split
from sklearn import metrics
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score, f1_score
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler

In [4]:
dia = pd.read_csv('data2.csv')
dia.head()

Age Gender Polyuria Polydipsia sudden weight loss weakness Obesity  \
0   40   Male       No        Yes                 No      Yes     Yes   
1   58   Male       No         No                 No      Yes      No   
2   41   Male      Yes         No                 No      Yes      No   
3   45   Male       No         No                Yes      Yes      No   
4   60   Male      Yes        Yes                Yes      Yes     Yes   

      class  
0  Positive  
1  Positive  
2  Positive  
3  Positive  
4  Positive

In [5]:
dia.describe()

Age
count  520.000000
mean    48.028846
std     12.151466
min     16.000000
25%     39.000000
50%     47.500000
75%     57.000000
max     90.000000

In [6]:
dia.dtypes

Age                    int64
Gender                object
Polyuria              object
Polydipsia            object
sudden weight loss    object
weakness              object
Obesity               object
class                 object
dtype: object

In [7]:
n_dia = LabelEncoder()
dia['Gender'] = n_dia.fit_transform(dia['Gender'].astype('str')) 
dia['Polyuria'] = n_dia.fit_transform(dia['Polyuria'].astype('str')) 
dia['Polydipsia'] = n_dia.fit_transform(dia['Polydipsia'].astype('str')) 
dia['sudden weight loss'] = n_dia.fit_transform(dia['sudden weight loss'].astype('str')) 
dia['weakness'] = n_dia.fit_transform(dia['weakness'].astype('str')) 
dia['Obesity'] = n_dia.fit_transform(dia['Obesity'].astype('str')) 
dia['class'] = n_dia.fit_transform(dia['class'].astype('str')) 
dia.head()

Age  Gender  Polyuria  Polydipsia  sudden weight loss  weakness  Obesity  \
0   40       1         0           1                   0         1        1   
1   58       1         0           0                   0         1        0   
2   41       1         1           0                   0         1        0   
3   45       1         0           0                   1         1        0   
4   60       1         1           1                   1         1        1   

   class  
0      1  
1      1  
2      1  
3      1  
4      1

In [8]:
rslt_df = dia[dia['class'] == 1]
rslt_df

Age  Gender  Polyuria  Polydipsia  sudden weight loss  weakness  Obesity  \
0     40       1         0           1                   0         1        1   
1     58       1         0           0                   0         1        0   
2     41       1         1           0                   0         1        0   
3     45       1         0           0                   1         1        0   
4     60       1         1           1                   1         1        1   
..   ...     ...       ...         ...                 ...       ...      ...   
513   62       0         1           1                   1         1        1   
514   54       0         1           1                   1         1        0   
515   39       0         1           1                   1         0        0   
516   48       0         1           1                   1         1        0   
517   58       0         1           1                   1         1        1   

     class  
0        1  
1        1  
2        1  
3        1  
4        1  
..     ...  
513      1  
514      1  
515      1  
516      1  
517      1  

[320 rows x 8 columns]

In [9]:
rslt_df = dia[dia['class'] == 0]
rslt_df

Age  Gender  Polyuria  Polydipsia  sudden weight loss  weakness  Obesity  \
200   40       1         0           1                   1         1        0   
201   28       1         0           0                   1         0        0   
202   37       1         0           0                   0         0        0   
203   34       1         0           0                   0         0        0   
204   30       1         0           0                   0         0        0   
..   ...     ...       ...         ...                 ...       ...      ...   
510   67       1         0           0                   0         1        0   
511   66       1         0           0                   0         1        0   
512   43       1         0           0                   0         0        0   
518   32       0         0           0                   0         1        0   
519   42       1         0           0                   0         0        0   

     class  
200      0  
201      0  
202      0  
203      0  
204      0  
..     ...  
510      0  
511      0  
512      0  
518      0  
519      0  

[200 rows x 8 columns]

In [10]:
X = dia.iloc[:, :-1].values
y = dia.iloc[:, 7]
print(y)

0      1
1      1
2      1
3      1
4      1
      ..
515    1
516    1
517    1
518    0
519    0
Name: class, Length: 520, dtype: int32


In [11]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3)

In [12]:
scaler = StandardScaler()
scaler.fit(X_train)
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

### Algorithms used for classification

In [13]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.neural_network import MLPClassifier

### 1. Decision Tree CLassifier

In [14]:
from sklearn import tree

In [15]:
dt = tree.DecisionTreeClassifier()
dt.fit(X_train, y_train)
pred_dt = dt.predict(X_test)
print(y_test)
print(pred_dt)
print(metrics.accuracy_score(y_test, pred_dt)*100)
print(confusion_matrix(y_test, pred_dt))
print(classification_report(y_test, pred_dt))

286    0
13     1
333    0
57     1
312    0
      ..
461    0
337    1
218    0
238    0
488    0
Name: class, Length: 156, dtype: int32
[0 1 0 0 0 1 0 0 1 0 0 0 0 1 1 1 1 1 0 1 0 1 1 1 1 0 1 1 1 0 1 1 1 0 0 0 1
 0 0 0 0 0 1 1 1 1 1 1 1 0 1 0 0 0 1 1 0 0 0 0 1 1 1 1 1 1 1 1 0 1 1 1 1 1
 1 0 1 1 1 1 1 0 0 1 1 1 1 1 0 1 0 1 0 0 0 1 1 1 1 0 1 1 0 1 0 1 1 1 0 1 0
 0 1 0 0 1 0 0 0 1 0 1 1 1 1 0 1 1 0 1 1 1 0 1 0 0 1 1 1 1 1 0 1 1 0 1 0 1
 0 1 1 0 1 0 0 0]
94.23076923076923
[[57  2]
 [ 7 90]]
              precision    recall  f1-score   support

           0       0.89      0.97      0.93        59
           1       0.98      0.93      0.95        97

    accuracy                           0.94       156
   macro avg       0.93      0.95      0.94       156
weighted avg       0.95      0.94      0.94       156



### 2. Naive Bayes Classifier

In [16]:
nb = GaussianNB()
nb.fit(X_train, y_train)
pred_nb = nb.predict(X_test)
print(y_test)
print(pred_nb)
print(metrics.accuracy_score(y_test, pred_nb)*100)
print(confusion_matrix(y_test, pred_nb))
print(classification_report(y_test, pred_nb))

286    0
13     1
333    0
57     1
312    0
      ..
461    0
337    1
218    0
238    0
488    0
Name: class, Length: 156, dtype: int32
[0 1 0 0 0 1 0 1 1 0 1 0 0 0 1 1 1 1 0 1 0 1 1 1 1 0 1 1 0 0 1 0 1 0 0 0 1
 1 1 1 0 0 1 0 1 0 1 1 1 1 1 0 0 0 0 1 0 0 0 0 1 1 1 1 1 1 1 1 0 1 1 1 1 1
 1 0 1 1 1 1 1 0 0 1 1 1 0 1 0 1 1 1 0 0 0 1 1 1 1 1 1 1 0 1 0 1 1 1 0 1 0
 0 1 0 1 1 1 1 0 0 0 1 1 1 1 0 1 1 0 1 1 1 0 1 0 0 1 1 1 1 1 1 1 1 0 1 0 1
 1 1 1 0 1 0 0 1]
85.25641025641025
[[47 12]
 [11 86]]
              precision    recall  f1-score   support

           0       0.81      0.80      0.80        59
           1       0.88      0.89      0.88        97

    accuracy                           0.85       156
   macro avg       0.84      0.84      0.84       156
weighted avg       0.85      0.85      0.85       156



### 3. Logistic Regression

In [17]:
lr = LogisticRegression()
lr.fit(X_train, y_train)
pred_lr = lr.predict(X_test)
print(y_test)
print(pred_lr)
print(metrics.accuracy_score(y_test, pred_lr)*100)
print(confusion_matrix(y_test, pred_lr))
print(classification_report(y_test, pred_lr))

286    0
13     1
333    0
57     1
312    0
      ..
461    0
337    1
218    0
238    0
488    0
Name: class, Length: 156, dtype: int32
[0 1 0 1 0 1 1 1 1 0 1 0 0 1 1 1 1 1 0 1 0 1 1 1 1 0 1 1 0 0 1 0 1 0 0 1 0
 1 0 1 0 0 1 0 1 1 1 1 1 1 1 0 0 0 1 1 0 0 0 0 1 1 1 1 1 1 1 1 0 0 1 1 1 1
 1 0 1 1 1 1 1 0 0 1 1 1 1 1 0 1 1 1 0 0 0 1 1 1 1 1 1 1 0 1 0 1 1 1 0 1 0
 0 1 0 1 1 1 1 0 1 0 1 1 1 1 1 1 1 0 1 1 1 0 1 1 0 1 1 1 1 1 1 1 1 0 1 0 1
 1 1 1 0 1 0 0 1]
87.17948717948718
[[45 14]
 [ 6 91]]
              precision    recall  f1-score   support

           0       0.88      0.76      0.82        59
           1       0.87      0.94      0.90        97

    accuracy                           0.87       156
   macro avg       0.87      0.85      0.86       156
weighted avg       0.87      0.87      0.87       156



### 4. K Nearest Neighbors Classifier

In [18]:
knn = KNeighborsClassifier()
knn.fit(X_train, y_train)
pred_knn = knn.predict(X_test)
print(y_test)
print(pred_knn)
print(metrics.accuracy_score(y_test, pred_knn)*100)
print(confusion_matrix(y_test, pred_knn))
print(classification_report(y_test, pred_knn))

286    0
13     1
333    0
57     1
312    0
      ..
461    0
337    1
218    0
238    0
488    0
Name: class, Length: 156, dtype: int32
[0 1 0 1 0 1 1 0 1 0 1 0 0 1 1 1 1 1 0 1 0 1 1 1 1 0 1 1 0 0 1 0 1 0 0 1 1
 0 1 1 0 0 1 0 1 1 1 1 0 1 1 0 0 0 1 1 0 0 0 0 1 1 1 1 0 1 1 1 0 1 1 1 1 1
 1 0 1 1 1 1 1 0 0 1 1 1 1 1 0 1 1 1 0 0 0 1 1 1 1 0 1 1 0 1 0 1 1 1 0 1 0
 0 1 0 0 1 1 0 0 1 0 1 1 1 1 1 1 1 0 1 1 1 0 1 1 0 1 1 1 1 1 0 1 1 1 1 1 1
 1 1 1 0 1 0 0 0]
91.02564102564102
[[50  9]
 [ 5 92]]
              precision    recall  f1-score   support

           0       0.91      0.85      0.88        59
           1       0.91      0.95      0.93        97

    accuracy                           0.91       156
   macro avg       0.91      0.90      0.90       156
weighted avg       0.91      0.91      0.91       156



### Different classifiers and their accuracy

In [20]:
final_data = pd.DataFrame({'Models': ['Decision Tree','NaiveBayes','Logistic Regression','K Nearest Neighbors Classifier'],
                          'Accuracy':[metrics.accuracy_score(y_test, pred_dt)*100,
                                     metrics.accuracy_score(y_test, pred_nb)*100,
                                     metrics.accuracy_score(y_test, pred_lr)*100,
                                     metrics.accuracy_score(y_test, pred_knn)*100]})

final_data

Models   Accuracy
0                   Decision Tree  94.230769
1                      NaiveBayes  85.256410
2             Logistic Regression  87.179487
3  K Nearest Neighbors Classifier  91.025641

### As mentioned above, DecisionTreeClassifier works best for the given problem

### Saving the model

In [ ]:
import pickle

In [ ]:
file_name = 'krupal_dt_model.pkl'
pickle.dump(dt, open(file_name, 'wb'))